### ISSUE TITLE
Compression level

### ISSUE THREAD

**Issue by shmuga** [sile/libflate#11]
Hi,

Is there any possibility to define compression level for gzip encoder?
I'm using next code for encoding and I found that comparing to Node.js implementation current lib has 2 times bigger resulting size. 

```rust
    use libflate::gzip::{Encoder, Decoder};

    // .......

    let mut encoder = Encoder::new(Vec::new())?;
    io::copy(&mut v.as_bytes(), &mut encoder)?;
    let compressed_bytes = encoder.finish().into_result()?;
```

**Comment by sile** [comment]
Currently, `libflate` provides only [DefaultLz77Encoder](https://docs.rs/libflate/0.1.12/libflate/lz77/struct.DefaultLz77Encoder.html) that has no "compression level" like feature and not optimized.
(Although it is possible to specify your own encoder, it is not easy to implement efficient one)
