### ISSUE TITLE
Not decompressing entire stream

### ISSUE THREAD

**Issue by coder543** [sile/libflate#13]
Something about the gzip encoder used to create the CommonCrawl archives doesn't play well with `libflate`. It only seems to decompress the first few hundred bytes.

[Example file.](https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2017-51/segments/1512948511435.4/wet/CC-MAIN-20171210235516-20171211015516-00000.warc.wet.gz)

If I `gunzip` it then `gzip` it again, `libflate` is able to decompress the entire file correctly... so, it's interesting.

**Comment by coder543** [comment]
Using `flate2`, I'm able to decompress the entire file, but I had to use [MultiGzDecoder](https://docs.rs/flate2/1.0.1/flate2/read/struct.MultiGzDecoder.html), so I think the issue is that the file consists of several Gzip streams in a sequence. Supposedly, the Gzip standard allows this.

**Comment by sile** [comment]
Thank you for your information.
I tried adding `gzip::MultiDecoder` at the commit https://github.com/sile/libflate/commit/deadd75c47431e1336acdaf58bd2652e4be6f6c8.
