### ISSUE TITLE
Panics on debug_assert failures

### ISSUE THREAD

**Issue by daniellockyer** [sile/libflate#15]
I am able to trigger 3 `debug_assert` failures by passing inputs to this library. I found them using honggfuzz and through the [usvg](https://github.com/RazrFalcon/usvg) library.

I opened issues over there but they are caused by this library:
* [Issue 1](https://github.com/RazrFalcon/usvg/issues/20)
* [Issue 2](https://github.com/RazrFalcon/usvg/issues/21)
* [Issue 3](https://github.com/RazrFalcon/usvg/issues/22)

The inputs I gave to that library are given, along with the backtraces. I figure there should be some checks and handling added somewhere.

**Comment by sile** [comment]
Thank you for reporting these problems.
I will investigate the causes.

**Comment by sile** [comment]
I fixed the problems and released [v0.1.16](https://github.com/sile/libflate/releases/tag/0.1.16).

**Comment by daniellockyer** [comment]
Excellent - thanks!
