### ISSUE TITLE
wrong gzip extra field

### ISSUE THREAD

**Issue by quininer** [sile/libflate#22]
In [your code that handles extra field](https://github.com/sile/libflate/blob/9d3956313676d7b269462181855b881ba8082528/src/gzip.rs#L480), you write an `id` before `xlen`.

The [rfc](https://tools.ietf.org/html/rfc1952#page-5) specifies extra field can have multiple subfields, but the extra field itself has no `id`.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ab6cbb9ec6dff73db8313aeb7308a358

**Comment by sile** [comment]
Thank you for reporting this problem. I fixed it at the commit https://github.com/sile/libflate/commit/e2899b3129229b35b213a138712529a98479e38b.
