### ISSUE TITLE
zlib::Encoder flush() behavior

### ISSUE THREAD

**Issue by z64** [sile/libflate#27]
I have a use case that requires the ability to do incremental writes to an encoder. Instead of `finish()`, I need to instead be able to call `flush()` (multiple times) and inspect the inner buffer.

See this comparison with the `flate2` crate which demonstrates the desired behvaior:

```rust
extern crate libflate;
extern crate flate2;

use flate2::{Compression, write::ZlibEncoder};
use libflate::zlib::Encoder;
use std::io::Write;

fn main() {
    let writes = [
        "fooooooooooooooooo",
        "bar",
        "baz",
    ];

    // libflate:
    let mut encoder = Encoder::new(Vec::new()).unwrap();
    for string in writes.iter() {
        encoder.write(string.as_bytes()).expect("Write failed");
    }
    encoder.flush().expect("Flush failed");
    println!("{:?}", encoder.as_inner_ref());

    // flate2:
    let mut encoder = ZlibEncoder::new(Vec::new(), Compression::default());
    for _ in 0..2 {
        for string in writes.iter() {
            encoder.write(string.as_bytes()).expect("Write failed");
        }
        encoder.flush().expect("Flush failed");
    }
    println!("{:?}", encoder.get_ref());
}
```
Which outputs (take note of the `0, 0, 255, 255` sync flush sequences)
```
[120, 156]
[120, 1, 74, 203, 71, 7, 73, 137, 69, 73, 137, 85, 0, 0, 0, 0, 255, 255, 74, 195, 33, 14, 0, 0, 0, 255, 255]
```
Does `libflate` support this? Perhaps I'm not using the API correctly?

**Comment by sam0x17** [comment]
I believe the c library does support flushing yes. I would consider asking the author of the bindings

**Comment by sile** [comment]
@z64 
Thank you for reporting this issue.
I have modified `libflate` to support this functionality (PR: #28). Could you confirm that the modified version satisfies your requirement?

**Comment by z64** [comment]
@sile Fantastic! I will take a look in a few hours. Thank you.
