### ISSUE TITLE
LZ77 compressor as a separate crate?

### ISSUE THREAD

**Issue by HybridEidolon** [sile/libflate#46]
I am working on a crate which implements a compressor and decompressor for a particular encoding of LZ77 used in several video games for asset compression. The LZ77 compressor in this crate is perfect for my needs, but I can't import it in isolation from the rest of the DEFLATE and gzip implementation, so the crate has to pull in dependencies it doesn't really need.

Would you consider making the LZ77 encoder a separate crate to make this sort of use case easier?

**Comment by sile** [comment]
Hi, thank you for creating this issue.
It is possible to simply separate [the LZ77 part](https://docs.rs/libflate/0.1.27/libflate/lz77/index.html
) of this crate into another crate, such as `libflate_lz77` (the current LZ77 implementation is very naive and not optimal, though). Is it sufficient for you?

**Comment by HybridEidolon** [comment]
Sure. My crate currently clone-and-owns the lz77 module and makes some minor adjustments to make it compatible with the lz77 implementation I am working with, and it works perfectly, although the compression ratio admittedly isn't the best.

**Comment by sile** [comment]
Published https://crates.io/crates/libflate_lz77.
