### ISSUE TITLE
Compression level 

### ISSUE THREAD

**Issue by Smotrov** [sile/libflate#55]
Hi all! 
Would appreciate it if someone will point me to an example showing **how to set a certain compression level** when I compress some data using libflate. 
Thank you in advance!

**Comment by sile** [comment]
Hi @Smotrov, thank you for reaching out.

In terms of API, you can specify a [`Lz77Encode`](https://docs.rs/libflate/1.0.2/libflate/lz77/trait.Lz77Encode.html) instance to control the compression level via the `EncodeOptions::with_lz77` method as follows:
```rust
// From: https://docs.rs/libflate/1.0.2/libflate/deflate/struct.EncodeOptions.html#example
use libflate::lz77::DefaultLz77Encoder;
use libflate::deflate::{Encoder, EncodeOptions};

let options = EncodeOptions::with_lz77(DefaultLz77Encoder::new());
let encoder = Encoder::with_options(Vec::new(), options);
```

However, unfortunately, the current `libflate` only provides [`DefaultLz77Encoder`](https://docs.rs/libflate/1.0.2/libflate/lz77/struct.DefaultLz77Encoder.html) as a practical built-in LZ77 encoder implementation and it doesn't have the capability to change the compression level.
(Actually, there is another [`Lz77Encode`](https://docs.rs/libflate/1.0.2/libflate/lz77/trait.Lz77Encode.html) implementation named [`NoCompressionLz77Encoder`](https://docs.rs/libflate/1.0.2/libflate/lz77/struct.NoCompressionLz77Encoder.html) but it seems to be of little use in practice)

**Comment by Smotrov** [comment]
Thank you very much @sile! 
Same story from GZIP?

**Comment by sile** [comment]
> Same story from GZIP?

Yes (cf. [libflate::gzip::EncodeOptions](https://docs.rs/libflate/1.0.2/libflate/gzip/struct.EncodeOptions.html)).

**Comment by Smotrov** [comment]
🙏

**Comment by Code7R** [comment]
> Hi @Smotrov, thank you for reaching out.
> 
> In terms of API, you can specify a [`Lz77Encode`](https://docs.rs/libflate/1.0.2/libflate/lz77/trait.Lz77Encode.html) instance to control the compression level via the `EncodeOptions::with_lz77` method as follows:
> 
> ```rust
> // From: https://docs.rs/libflate/1.0.2/libflate/deflate/struct.EncodeOptions.html#example
> use libflate::lz77::DefaultLz77Encoder;
> use libflate::deflate::{Encoder, EncodeOptions};
> 
> let options = EncodeOptions::with_lz77(DefaultLz77Encoder::new());
> let encoder = Encoder::with_options(Vec::new(), options);
> ```
> 
> However, unfortunately, the current `libflate` only provides [`DefaultLz77Encoder`](https://docs.rs/libflate/1.0.2/libflate/lz77/struct.DefaultLz77Encoder.html) as a practical built-in LZ77 encoder implementation and it doesn't have the capability to change the compression level. (Actually, there is another [`Lz77Encode`](https://docs.rs/libflate/1.0.2/libflate/lz77/trait.Lz77Encode.html) implementation named [`NoCompressionLz77Encoder`](https://docs.rs/libflate/1.0.2/libflate/lz77/struct.NoCompressionLz77Encoder.html) but it seems to be of little use in practice)

I fail to see why this story was closed. The issue is no resolved. Even with:

> let options = EncodeOptions::with_lz77(DefaultLz77Encoder::new());

there is no way to set the compression level. You also cannot push it through header, the field is private.
