### ISSUE TITLE
LZ77 decoder?

### ISSUE THREAD

**Issue by Skirmisher** [sile/libflate#59]
Is there interest in implementing/exposing a raw LZ77 decoder to go along with the encoder? This would be great for a project I'm writing, since it also needs to handle zlib streams, and pulling in libflate alone simplifies things greatly, as opposed to depending on a separate crate for handling LZ77. (Though at the moment the separate crate I'm using is actually an old sample living in a git repo only, which is why it's somewhat of an issue.)

**Comment by sile** [comment]
Thank you for reaching out.
It sounds interesting, so I tried implementing `libflate_lz77::Lz77Decoder` in #60.
The PR is still draft and I'd like to get your feedback on whether the `Lz77Decoder` interface satisfies your need.

**Comment by Skirmisher** [comment]
Thank you! I'll give it a try once I'm able.
