### ISSUE TITLE
UB in the public safe API - where to report?

### ISSUE THREAD

**Issue by jorgecarleitao** [sile/libflate#63]
I was able to trigger undefined behavior (according to MIRI) using the public safe API of `libflate` (v1.1.1). Is there a private channel where this can be communicated and discussed, or it is ok to report it here?

**Comment by jorgecarleitao** [comment]
After some investigations, the UB is being triggered on the dependency rle-decode-fast. Closing this. Sorry for the noise :/

**Comment by sile** [comment]
Don't mind. Thank you anyway😄

**Comment by jorgecarleitao** [comment]
fwiw, our CI is getting MIRI failures from rle-decode-fast for some time now. Together with dark-arts folks, we were able to identify the root cause and have a fix: https://github.com/WanzenBug/rle-decode-helper/pull/8 . Unfortunately, the crate seems un-mainained. Is there a path forward here?

**Comment by sile** [comment]
It seems the issue mentioned in the above comment has already been resolved 🎉
