### ISSUE TITLE
Some cooperation?

### ISSUE THREAD

**Issue by oyvindln** [sile/libflate#8]
Hi. 

So I've been thinking about making a post on the rust forums about collaborating some efforts to design a full rust replacement for the flate2 crate (that uses c libraries) as DEFLATE a very widely used compression format that's even used in the rust compiler. I thougt I would ask about some cooperation here first.

I've been working on my own pure rust [deflate encoder](https://crates.io/crates/deflate) for a long time now. My original goal was to make a companion to the [inflate](https://crates.io/crates/inflate) crate (libflate didn't exist back then.) This crate(libflate) seems to be much more complete, and generally faster than inflate though, and the code seem cleaner and more rust-like. (I have a tool for doing comparisons here: https://github.com/oyvindln/compression-testing). The encoder part of libflate is however quite bare-bones compared to flate2. As my deflate crate is more featured, compresses a lot more, and is generally faster at compressing than libflate at comparable compression levels (but not as good as flate2 speed-wise), I was wondering if you were interested in trying to leverage this work to improve the decoding part of libflate (not entirely sure what the best approach would be), rather than having several competing deflate crates.

I hope this doesn't come off too much as self-promotion.

**Comment by sile** [comment]
Thank you for contacting me.

Currently, I'm not planning to improve the efficiency of the encoding part of `libflate`.
(And I have no ambition to make this library the defacto standard.)

In addition, I think it is a very interesting task to try to implement a pure Rust DEFLATE decoder that is faster than C alternatives.

So, I would like to support your efforts, if I can cooperate on the implementation side.
(However, at least for a while, I can not spend too much time on this task ...)

**Comment by sile** [comment]
Since a long period of time elapsed without no reaction, I will close this PR.
